/**
 * Mock data for development - IDs match live Supabase data
 */

// Live Supabase IDs
export const LIVE_IDS = {
  tenant: 'df737c3b-d4ba-4bc9-9baf-da43f040878c',
  location: '25f79abd-bdda-4bcb-a535-d6d9939a9075',
  camp: 'f4d9eeca-3848-497d-8c73-8fab64338758',
}

export const mockTenant = {
  id: LIVE_IDS.tenant,
  name: 'Empowered Sports Camp',
  slug: 'empowered',
  logo_url: null,
  primary_color: '#CCFF00',
  secondary_color: '#FF2DCE',
  contact_email: 'info@empoweredsportscamp.com',
  contact_phone: '(813) 555-0100',
  city: 'Tampa',
  state: 'FL',
}

export const mockLocation = {
  id: LIVE_IDS.location,
  tenant_id: mockTenant.id,
  name: 'Main Campus',
  address: '123 Sports Way',
  city: 'Tampa',
  state: 'FL',
  zip: '33601',
}

export const mockCamps = [
  {
    id: LIVE_IDS.camp,
    tenant_id: mockTenant.id,
    location_id: mockLocation.id,
    name: 'Summer Basketball Camp 2025',
    slug: 'summer-basketball-2025',
    description: 'Join us for an exciting week of basketball training, skill development, and fun! Our experienced coaches will help players of all skill levels improve their game.',
    sport: 'Basketball',
    age_min: 5,
    age_max: 14,
    start_date: '2025-06-16',
    end_date: '2025-06-20',
    start_time: '09:00',
    end_time: '15:00',
    capacity: 50,
    price: 299.00,
    early_bird_price: 249.00,
    early_bird_deadline: '2025-05-01',
    registration_open: true,
    featured: true,
    image_url: '/images/basketball-camp.jpg',
    location: mockLocation,
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440011',
    tenant_id: mockTenant.id,
    location_id: mockLocation.id,
    name: 'Soccer Skills Academy',
    slug: 'soccer-skills-2025',
    description: 'Develop your soccer skills with professional coaching. Perfect for beginners and intermediate players looking to take their game to the next level.',
    sport: 'Soccer',
    age_min: 5,
    age_max: 12,
    start_date: '2025-06-23',
    end_date: '2025-06-27',
    start_time: '09:00',
    end_time: '14:00',
    capacity: 40,
    price: 279.00,
    early_bird_price: 229.00,
    early_bird_deadline: '2025-05-15',
    registration_open: true,
    featured: true,
    image_url: '/images/soccer-camp.jpg',
    location: mockLocation,
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440012',
    tenant_id: mockTenant.id,
    location_id: mockLocation.id,
    name: 'Multi-Sport Camp',
    slug: 'multi-sport-2025',
    description: 'Try a variety of sports including basketball, soccer, flag football, and more! Great for young athletes who want to explore different activities.',
    sport: 'Multi-Sport',
    age_min: 5,
    age_max: 10,
    start_date: '2025-07-07',
    end_date: '2025-07-11',
    start_time: '08:30',
    end_time: '15:30',
    capacity: 60,
    price: 319.00,
    early_bird_price: null,
    early_bird_deadline: null,
    registration_open: true,
    featured: false,
    image_url: '/images/multi-sport-camp.jpg',
    location: mockLocation,
  },
]

export const mockAddons = [
  {
    id: '550e8400-e29b-41d4-a716-446655440020',
    camp_id: mockCamps[0].id,
    name: 'Camp T-Shirt',
    description: 'Official camp t-shirt with your name on the back',
    price: 25.00,
    max_quantity: 3,
    active: true,
    variants: [
      { id: 'v1', name: 'Youth S', price_adjustment: 0 },
      { id: 'v2', name: 'Youth M', price_adjustment: 0 },
      { id: 'v3', name: 'Youth L', price_adjustment: 0 },
      { id: 'v4', name: 'Adult S', price_adjustment: 5 },
      { id: 'v5', name: 'Adult M', price_adjustment: 5 },
      { id: 'v6', name: 'Adult L', price_adjustment: 5 },
    ],
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440021',
    camp_id: mockCamps[0].id,
    name: 'Extended Care (7:30 AM - 9:00 AM)',
    description: 'Early drop-off option for working parents',
    price: 50.00,
    max_quantity: 1,
    active: true,
    variants: [],
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440022',
    camp_id: mockCamps[0].id,
    name: 'Extended Care (3:00 PM - 5:30 PM)',
    description: 'Late pick-up option for working parents',
    price: 50.00,
    max_quantity: 1,
    active: true,
    variants: [],
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440023',
    camp_id: mockCamps[0].id,
    name: 'Lunch Package (5 days)',
    description: 'Hot lunch provided each day of camp',
    price: 45.00,
    max_quantity: 1,
    active: true,
    variants: [],
  },
]

export const mockUser = {
  id: '550e8400-e29b-41d4-a716-446655440099',
  email: 'parent@example.com',
  user_metadata: {
    full_name: 'John Parent',
  },
}

export const mockAthletes = [
  {
    id: '550e8400-e29b-41d4-a716-446655440030',
    parent_id: mockUser.id,
    first_name: 'Emma',
    last_name: 'Parent',
    date_of_birth: '2015-03-15',
    gender: 'female',
    shirt_size: 'Youth M',
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440031',
    parent_id: mockUser.id,
    first_name: 'Jack',
    last_name: 'Parent',
    date_of_birth: '2017-08-22',
    gender: 'male',
    shirt_size: 'Youth S',
  },
]

/**
 * Mock data for public_camp_cards view
 * Used by the Find Camps page
 */
export const mockPublicCampCards = [
  {
    id: LIVE_IDS.camp,
    slug: 'summer-basketball-2025',
    name: 'Summer Basketball Camp 2025',
    description: 'Join us for an exciting week of basketball training, skill development, and fun! Our experienced coaches will help players of all skill levels improve their game.',
    program_type: 'all_girls_sports_camp',
    start_date: '2025-06-16',
    end_date: '2025-06-20',
    daily_start_time: '09:00:00',
    daily_end_time: '15:00:00',
    min_age: 5,
    max_age: 14,
    min_grade: null,
    max_grade: null,
    max_capacity: 50,
    price: 29900, // cents
    early_bird_price: 24900,
    early_bird_deadline: '2025-05-01',
    image_url: '/images/basketball-camp.jpg',
    highlights: ['Expert coaching', 'Skill development', 'Team building', 'Fun competitions'],
    sports_offered: ['Basketball'],
    featured: true,
    status: 'open',
    tenant_id: LIVE_IDS.tenant,
    location_id: LIVE_IDS.location,
    location_name: 'Main Campus',
    location_address: '123 Sports Way',
    city: 'Tampa',
    state: 'FL',
    zip_code: '33601',
    latitude: 27.9506,
    longitude: -82.4572,
    indoor: true,
    tenant_name: 'Empowered Sports Camp',
    tenant_slug: 'empowered',
    spots_remaining: 42,
    current_price: 24900,
    is_full: false,
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440011',
    slug: 'soccer-skills-2025',
    name: 'Soccer Skills Academy',
    description: 'Develop your soccer skills with professional coaching. Perfect for beginners and intermediate players looking to take their game to the next level.',
    program_type: 'all_girls_sports_camp',
    start_date: '2025-06-23',
    end_date: '2025-06-27',
    daily_start_time: '09:00:00',
    daily_end_time: '14:00:00',
    min_age: 5,
    max_age: 12,
    min_grade: null,
    max_grade: null,
    max_capacity: 40,
    price: 27900,
    early_bird_price: 22900,
    early_bird_deadline: '2025-05-15',
    image_url: '/images/soccer-camp.jpg',
    highlights: ['Professional coaching', 'Small group training', 'Game strategies'],
    sports_offered: ['Soccer'],
    featured: true,
    status: 'open',
    tenant_id: LIVE_IDS.tenant,
    location_id: LIVE_IDS.location,
    location_name: 'Main Campus',
    location_address: '123 Sports Way',
    city: 'Tampa',
    state: 'FL',
    zip_code: '33601',
    latitude: 27.9506,
    longitude: -82.4572,
    indoor: false,
    tenant_name: 'Empowered Sports Camp',
    tenant_slug: 'empowered',
    spots_remaining: 28,
    current_price: 22900,
    is_full: false,
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440012',
    slug: 'multi-sport-2025',
    name: 'Multi-Sport Camp',
    description: 'Try a variety of sports including basketball, soccer, flag football, and more! Great for young athletes who want to explore different activities.',
    program_type: 'all_girls_sports_camp',
    start_date: '2025-07-07',
    end_date: '2025-07-11',
    daily_start_time: '08:30:00',
    daily_end_time: '15:30:00',
    min_age: 5,
    max_age: 10,
    min_grade: null,
    max_grade: null,
    max_capacity: 60,
    price: 31900,
    early_bird_price: null,
    early_bird_deadline: null,
    image_url: '/images/multi-sport-camp.jpg',
    highlights: ['Multiple sports', 'Fun activities', 'New friendships'],
    sports_offered: ['Basketball', 'Soccer', 'Flag Football', 'Volleyball'],
    featured: false,
    status: 'open',
    tenant_id: LIVE_IDS.tenant,
    location_id: LIVE_IDS.location,
    location_name: 'Main Campus',
    location_address: '123 Sports Way',
    city: 'Tampa',
    state: 'FL',
    zip_code: '33601',
    latitude: 27.9506,
    longitude: -82.4572,
    indoor: true,
    tenant_name: 'Empowered Sports Camp',
    tenant_slug: 'empowered',
    spots_remaining: 55,
    current_price: 31900,
    is_full: false,
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440013',
    slug: 'cit-program-2025',
    name: 'CIT Leadership Program',
    description: 'Our Counselor-in-Training program for teens. Develop leadership skills while learning to coach younger athletes.',
    program_type: 'cit_program',
    start_date: '2025-06-16',
    end_date: '2025-08-08',
    daily_start_time: '08:00:00',
    daily_end_time: '16:00:00',
    min_age: 14,
    max_age: 17,
    min_grade: 9,
    max_grade: 12,
    max_capacity: 20,
    price: 59900,
    early_bird_price: 54900,
    early_bird_deadline: '2025-04-15',
    image_url: '/images/cit-program.jpg',
    highlights: ['Leadership training', 'Coaching experience', 'Community service hours', 'Resume builder'],
    sports_offered: ['Leadership', 'All Sports'],
    featured: true,
    status: 'open',
    tenant_id: LIVE_IDS.tenant,
    location_id: LIVE_IDS.location,
    location_name: 'Main Campus',
    location_address: '123 Sports Way',
    city: 'Tampa',
    state: 'FL',
    zip_code: '33601',
    latitude: 27.9506,
    longitude: -82.4572,
    indoor: true,
    tenant_name: 'Empowered Sports Camp',
    tenant_slug: 'empowered',
    spots_remaining: 8,
    current_price: 54900,
    is_full: false,
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440014',
    slug: 'volleyball-intensive-2025',
    name: 'Volleyball Intensive',
    description: 'Advanced volleyball training for competitive players. Work on serving, setting, spiking, and game strategy.',
    program_type: 'volleyball_clinic',
    start_date: '2025-07-14',
    end_date: '2025-07-18',
    daily_start_time: '09:00:00',
    daily_end_time: '15:00:00',
    min_age: 10,
    max_age: 16,
    min_grade: 5,
    max_grade: 10,
    max_capacity: 24,
    price: 34900,
    early_bird_price: 29900,
    early_bird_deadline: '2025-06-01',
    image_url: '/images/volleyball-camp.jpg',
    highlights: ['Advanced techniques', 'Video analysis', 'Position-specific training'],
    sports_offered: ['Volleyball'],
    featured: false,
    status: 'open',
    tenant_id: LIVE_IDS.tenant,
    location_id: LIVE_IDS.location,
    location_name: 'Main Campus',
    location_address: '123 Sports Way',
    city: 'Tampa',
    state: 'FL',
    zip_code: '33601',
    latitude: 27.9506,
    longitude: -82.4572,
    indoor: true,
    tenant_name: 'Empowered Sports Camp',
    tenant_slug: 'empowered',
    spots_remaining: 0,
    current_price: 29900,
    is_full: true,
  },
  {
    id: '550e8400-e29b-41d4-a716-446655440015',
    slug: 'chicago-summer-week-1',
    name: 'Chicago Summer Week 1',
    description: 'Kick off your summer with our flagship multi-sport camp in Chicago. Experience 7 different sports in one action-packed week!',
    program_type: 'all_girls_sports_camp',
    start_date: '2025-06-09',
    end_date: '2025-06-13',
    daily_start_time: '09:00:00',
    daily_end_time: '15:00:00',
    min_age: 6,
    max_age: 12,
    min_grade: 1,
    max_grade: 6,
    max_capacity: 50,
    price: 29900,
    early_bird_price: 26900,
    early_bird_deadline: '2025-05-01',
    image_url: '/images/chicago-camp.jpg',
    highlights: ['7 different sports', 'All-female coaching', 'Confidence building', 'New friendships'],
    sports_offered: ['Soccer', 'Basketball', 'Volleyball', 'Flag Football', 'Lacrosse', 'Tennis', 'Track'],
    featured: true,
    status: 'open',
    tenant_id: '550e8400-e29b-41d4-a716-446655440100',
    location_id: '550e8400-e29b-41d4-a716-446655440101',
    location_name: 'Lincoln Park Athletic Field',
    location_address: '2045 N Lincoln Park West',
    city: 'Chicago',
    state: 'IL',
    zip_code: '60614',
    latitude: 41.9220,
    longitude: -87.6385,
    indoor: false,
    tenant_name: 'Empowered Athletes Chicago',
    tenant_slug: 'chicago',
    spots_remaining: 35,
    current_price: 26900,
    is_full: false,
  },
]
