/**
 * Reports Service
 *
 * PDF & KPI report generation service for Empowered Sports Camp.
 *
 * Handles generation of:
 * - Session-level PDF reports (attendance, KPIs, revenue, incentives)
 * - Camp day end-of-day reports
 * - Curriculum PDF exports for staff
 * - Group reports for directors
 */

import { prisma } from '@/lib/db/client'
import { jsPDF } from 'jspdf'
import 'jspdf-autotable'

// Extend jsPDF type for autotable
declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF
    lastAutoTable: { finalY: number }
  }
}

// =============================================================================
// Types
// =============================================================================

export type ReportType = 'SESSION' | 'DAY' | 'CURRICULUM' | 'GROUP'

export interface PdfReportResult {
  pdfBase64: string | null
  filename: string
  generatedAt: string
}

export interface SessionReportData {
  campSession: {
    id: string
    name: string
    startDate: string
    endDate: string
    location: string
  }
  attendance: {
    totalEnrolled: number
    averageDaily: number
    checkInRate: number
  }
  revenue: {
    grossRevenue: number
    upsells: number
    arpc: number
  }
  incentives: {
    totalEarned: number
    bonuses: number
  }
  kpis: {
    csatScore: number | null
    incidentCount: number
    staffPerformance: number | null
  }
}

export interface CampDayReportData {
  campDay: {
    id: string
    date: string
    dayNumber: number
    campName: string
  }
  attendance: {
    enrolled: number
    checkedIn: number
    checkedOut: number
    noShows: number
  }
  incidents: {
    count: number
    details: string[]
  }
  scheduleCompletion: number
  notes: string | null
}

export interface CurriculumExportData {
  curriculum: {
    id: string
    title: string
    description: string | null
  }
  blocks: {
    title: string
    duration: number
    description: string | null
    order: number
    startTime?: string
    endTime?: string
  }[]
}

export interface GroupReportData {
  camp: {
    id: string
    name: string
    date: string
  }
  groups: {
    name: string
    color: string
    campers: {
      name: string
      age: number
      grade: string
    }[]
    staff: string[]
  }[]
}

// =============================================================================
// PDF Generation Helpers
// =============================================================================

function addHeader(doc: jsPDF, title: string, subtitle?: string) {
  // Empowered Athletes branding
  doc.setFillColor(0, 0, 0) // Black header
  doc.rect(0, 0, 220, 30, 'F')

  doc.setTextColor(204, 255, 0) // Neon green
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('EMPOWERED ATHLETES', 15, 15)

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(12)
  doc.text(title, 15, 24)

  if (subtitle) {
    doc.setTextColor(150, 150, 150)
    doc.setFontSize(10)
    doc.text(subtitle, 15, 38)
  }

  // Reset colors
  doc.setTextColor(0, 0, 0)
}

function addFooter(doc: jsPDF, pageNumber: number) {
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(8)
  doc.setTextColor(128, 128, 128)
  doc.text(
    `Generated by Empowered Athletes Camp Management | Page ${pageNumber}`,
    105,
    pageHeight - 10,
    { align: 'center' }
  )
  doc.text(new Date().toLocaleString(), 195, pageHeight - 10, { align: 'right' })
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
  }).format(amount)
}

function formatDate(dateString: string): string {
  return new Date(dateString).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

// =============================================================================
// Service Functions
// =============================================================================

/**
 * Generate a full PDF report for a camp session
 * Includes attendance, KPIs, revenue, and incentives data.
 */
export async function generateSessionPdfReport(params: {
  campSessionId: string
  tenantId: string
  role: string
}): Promise<{ data: PdfReportResult | null; error: Error | null }> {
  try {
    const { campSessionId, tenantId } = params

    // Fetch session data with registrations
    const camp = await prisma.camp.findFirst({
      where: {
        id: campSessionId,
        tenantId,
      },
      include: {
        tenant: true,
        location: true,
        registrations: {
          where: { status: 'confirmed' },
        },
        campDays: {
          include: {
            attendance: true,
            incidents: true,
          },
        },
      },
    })

    if (!camp) {
      return { data: null, error: new Error('Camp session not found') }
    }

    // Calculate metrics
    const totalEnrolled = camp.registrations.length
    const grossRevenue = camp.registrations.reduce((sum, r) => sum + (r.totalPriceCents || 0), 0) / 100
    const arpc = totalEnrolled > 0 ? grossRevenue / totalEnrolled : 0

    // Calculate attendance metrics
    let totalCheckIns = 0
    let totalExpected = 0
    for (const day of camp.campDays) {
      totalCheckIns += day.attendance.filter((a) => a.checkInTime).length
      totalExpected += totalEnrolled
    }
    const checkInRate = totalExpected > 0 ? (totalCheckIns / totalExpected) * 100 : 0
    const averageDaily = camp.campDays.length > 0 ? totalCheckIns / camp.campDays.length : 0

    // Count incidents
    const incidentCount = camp.campDays.reduce((sum, day) => sum + day.incidents.length, 0)

    // Generate PDF
    const doc = new jsPDF()

    addHeader(doc, 'SESSION REPORT', `${camp.name} | ${camp.tenant?.name || 'Unknown Tenant'}`)

    let yPos = 45

    // Session Info
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Session Details', 15, yPos)
    yPos += 8

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Camp: ${camp.name}`, 15, yPos)
    yPos += 6
    doc.text(`Location: ${camp.location?.name || 'N/A'}`, 15, yPos)
    yPos += 6
    doc.text(`Dates: ${formatDate(camp.startDate.toISOString())} - ${formatDate(camp.endDate.toISOString())}`, 15, yPos)
    yPos += 15

    // Attendance Section
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Attendance', 15, yPos)
    yPos += 8

    doc.autoTable({
      startY: yPos,
      head: [['Metric', 'Value']],
      body: [
        ['Total Enrolled', totalEnrolled.toString()],
        ['Average Daily Attendance', averageDaily.toFixed(1)],
        ['Check-In Rate', `${checkInRate.toFixed(1)}%`],
      ],
      theme: 'striped',
      headStyles: { fillColor: [0, 0, 0], textColor: [204, 255, 0] },
      margin: { left: 15 },
      tableWidth: 80,
    })

    yPos = doc.lastAutoTable.finalY + 15

    // Revenue Section
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Revenue', 15, yPos)
    yPos += 8

    doc.autoTable({
      startY: yPos,
      head: [['Metric', 'Value']],
      body: [
        ['Gross Revenue', formatCurrency(grossRevenue)],
        ['ARPC (Avg Revenue Per Camper)', formatCurrency(arpc)],
        ['Royalty (10%)', formatCurrency(grossRevenue * 0.1)],
      ],
      theme: 'striped',
      headStyles: { fillColor: [0, 0, 0], textColor: [204, 255, 0] },
      margin: { left: 15 },
      tableWidth: 80,
    })

    yPos = doc.lastAutoTable.finalY + 15

    // KPIs Section
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Key Performance Indicators', 15, yPos)
    yPos += 8

    doc.autoTable({
      startY: yPos,
      head: [['KPI', 'Value']],
      body: [
        ['Incident Count', incidentCount.toString()],
        ['Days Completed', `${camp.campDays.length}`],
      ],
      theme: 'striped',
      headStyles: { fillColor: [0, 0, 0], textColor: [204, 255, 0] },
      margin: { left: 15 },
      tableWidth: 80,
    })

    addFooter(doc, 1)

    const pdfBase64 = doc.output('datauristring')
    const filename = `session-report-${camp.name.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`

    return {
      data: {
        pdfBase64,
        filename,
        generatedAt: new Date().toISOString(),
      },
      error: null,
    }
  } catch (error) {
    console.error('[Reports] Failed to generate session PDF:', error)
    return { data: null, error: error as Error }
  }
}

/**
 * Generate end-of-day PDF report for Camp Day flow
 */
export async function generateCampDayPdfReport(params: {
  campDayId: string
  tenantId: string
  role: string
}): Promise<{ data: PdfReportResult | null; error: Error | null }> {
  try {
    const { campDayId, tenantId } = params

    const campDay = await prisma.campDay.findFirst({
      where: {
        id: campDayId,
        camp: { tenantId },
      },
      include: {
        camp: {
          include: {
            tenant: true,
            registrations: { where: { status: 'confirmed' } },
          },
        },
        attendance: {
          include: {
            athlete: true,
          },
        },
        incidents: true,
      },
    })

    if (!campDay) {
      return { data: null, error: new Error('Camp day not found') }
    }

    const enrolled = campDay.camp.registrations.length
    const checkedIn = campDay.attendance.filter((a) => a.checkInTime).length
    const checkedOut = campDay.attendance.filter((a) => a.checkOutTime).length
    const noShows = enrolled - checkedIn

    // Generate PDF
    const doc = new jsPDF()

    addHeader(doc, 'DAILY REPORT', `Day ${campDay.dayNumber} | ${campDay.camp.name}`)

    let yPos = 45

    // Day Info
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Day Summary', 15, yPos)
    yPos += 8

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    doc.text(`Date: ${formatDate(campDay.date.toISOString())}`, 15, yPos)
    yPos += 6
    doc.text(`Camp: ${campDay.camp.name}`, 15, yPos)
    yPos += 6
    doc.text(`Day Number: ${campDay.dayNumber}`, 15, yPos)
    yPos += 15

    // Attendance Table
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Attendance', 15, yPos)
    yPos += 8

    doc.autoTable({
      startY: yPos,
      head: [['Status', 'Count', 'Percentage']],
      body: [
        ['Expected', enrolled.toString(), '100%'],
        ['Checked In', checkedIn.toString(), `${((checkedIn / enrolled) * 100 || 0).toFixed(1)}%`],
        ['Checked Out', checkedOut.toString(), `${((checkedOut / enrolled) * 100 || 0).toFixed(1)}%`],
        ['No Shows', noShows.toString(), `${((noShows / enrolled) * 100 || 0).toFixed(1)}%`],
      ],
      theme: 'striped',
      headStyles: { fillColor: [0, 0, 0], textColor: [204, 255, 0] },
      margin: { left: 15 },
    })

    yPos = doc.lastAutoTable.finalY + 15

    // Incidents Section
    if (campDay.incidents.length > 0) {
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      doc.text('Incidents', 15, yPos)
      yPos += 8

      doc.autoTable({
        startY: yPos,
        head: [['Type', 'Description', 'Severity']],
        body: campDay.incidents.map((i) => [
          i.incidentType || 'General',
          i.description || 'No description',
          i.severity || 'Low',
        ]),
        theme: 'striped',
        headStyles: { fillColor: [0, 0, 0], textColor: [204, 255, 0] },
        margin: { left: 15 },
      })

      yPos = doc.lastAutoTable.finalY + 15
    }

    // Notes
    if (campDay.notes) {
      doc.setFontSize(14)
      doc.setFont('helvetica', 'bold')
      doc.text('Notes', 15, yPos)
      yPos += 8

      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      const splitNotes = doc.splitTextToSize(campDay.notes, 180)
      doc.text(splitNotes, 15, yPos)
    }

    addFooter(doc, 1)

    const pdfBase64 = doc.output('datauristring')
    const filename = `daily-report-day${campDay.dayNumber}-${new Date().toISOString().split('T')[0]}.pdf`

    return {
      data: {
        pdfBase64,
        filename,
        generatedAt: new Date().toISOString(),
      },
      error: null,
    }
  } catch (error) {
    console.error('[Reports] Failed to generate camp day PDF:', error)
    return { data: null, error: error as Error }
  }
}

/**
 * Export curriculum/schedule as a printable PDF for staff
 */
export async function exportCurriculumPdf(params: {
  curriculumId: string
  tenantId: string
  role: string
}): Promise<{ data: PdfReportResult | null; error: Error | null }> {
  try {
    const { curriculumId, tenantId } = params

    const template = await prisma.scheduleTemplate.findFirst({
      where: {
        id: curriculumId,
        OR: [{ licenseeId: tenantId }, { isGlobal: true }],
      },
      include: {
        blocks: {
          orderBy: { orderIndex: 'asc' },
        },
      },
    })

    if (!template) {
      return { data: null, error: new Error('Curriculum not found') }
    }

    // Generate PDF
    const doc = new jsPDF()

    addHeader(doc, 'CURRICULUM', template.name)

    let yPos = 45

    // Description
    if (template.description) {
      doc.setFontSize(10)
      doc.setFont('helvetica', 'italic')
      const splitDesc = doc.splitTextToSize(template.description, 180)
      doc.text(splitDesc, 15, yPos)
      yPos += splitDesc.length * 5 + 10
    }

    // Schedule Blocks
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Schedule', 15, yPos)
    yPos += 8

    const blockRows = template.blocks.map((block) => {
      const startTime = block.startTime.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
      const endTime = block.endTime.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })
      const duration = Math.round((block.endTime.getTime() - block.startTime.getTime()) / 60000)
      return [
        `${startTime} - ${endTime}`,
        block.label,
        `${duration} min`,
        block.description || '-',
      ]
    })

    doc.autoTable({
      startY: yPos,
      head: [['Time', 'Activity', 'Duration', 'Notes']],
      body: blockRows,
      theme: 'striped',
      headStyles: { fillColor: [0, 0, 0], textColor: [204, 255, 0] },
      margin: { left: 15 },
      columnStyles: {
        0: { cellWidth: 35 },
        1: { cellWidth: 50 },
        2: { cellWidth: 25 },
        3: { cellWidth: 70 },
      },
    })

    addFooter(doc, 1)

    const pdfBase64 = doc.output('datauristring')
    const filename = `curriculum-${template.name.replace(/\s+/g, '-').toLowerCase()}.pdf`

    return {
      data: {
        pdfBase64,
        filename,
        generatedAt: new Date().toISOString(),
      },
      error: null,
    }
  } catch (error) {
    console.error('[Reports] Failed to export curriculum PDF:', error)
    return { data: null, error: error as Error }
  }
}

/**
 * Generate group report PDF for directors
 * Shows all groups with their campers and staff assignments
 */
export async function generateGroupReportPdf(params: {
  campId: string
  tenantId: string
}): Promise<{ data: PdfReportResult | null; error: Error | null }> {
  try {
    const { campId, tenantId } = params

    const camp = await prisma.camp.findFirst({
      where: {
        id: campId,
        tenantId,
      },
      include: {
        tenant: true,
        campGroups: {
          include: {
            camperSessionData: {
              include: {
                athlete: true,
              },
            },
          },
        },
      },
    })

    if (!camp) {
      return { data: null, error: new Error('Camp not found') }
    }

    // Generate PDF
    const doc = new jsPDF()

    addHeader(doc, 'GROUP ROSTER', camp.name)

    let yPos = 45

    doc.setFontSize(10)
    doc.text(`Date: ${formatDate(camp.startDate.toISOString())}`, 15, yPos)
    yPos += 6
    doc.text(`Total Groups: ${camp.campGroups.length}`, 15, yPos)
    yPos += 15

    // Each group
    for (const group of camp.campGroups) {
      // Check if we need a new page
      if (yPos > 250) {
        doc.addPage()
        addHeader(doc, 'GROUP ROSTER (continued)', camp.name)
        yPos = 45
      }

      // Group header with color indicator
      doc.setFillColor(
        group.groupColor === 'pink' ? 255 : 128,
        group.groupColor === 'pink' ? 192 : 0,
        group.groupColor === 'purple' ? 128 : 203
      )
      doc.rect(15, yPos - 5, 180, 8, 'F')

      doc.setFontSize(12)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(255, 255, 255)
      doc.text(`${group.groupName || `Group ${group.groupNumber}`} (${group.groupColor?.toUpperCase() || 'N/A'})`, 17, yPos)
      doc.setTextColor(0, 0, 0)
      yPos += 10

      // Campers in group
      const camperRows = group.camperSessionData.map((csd: { athlete: { firstName: string; lastName: string; grade?: string | null } }, idx: number) => {
        const athlete = csd.athlete
        return [
          (idx + 1).toString(),
          athlete ? `${athlete.firstName} ${athlete.lastName}` : 'Unknown',
          athlete?.grade?.toString() || '-',
        ]
      })

      if (camperRows.length > 0) {
        doc.autoTable({
          startY: yPos,
          head: [['#', 'Camper Name', 'Grade']],
          body: camperRows,
          theme: 'plain',
          headStyles: { fillColor: [240, 240, 240], textColor: [0, 0, 0], fontStyle: 'bold' },
          margin: { left: 15 },
          tableWidth: 100,
        })
        yPos = doc.lastAutoTable.finalY + 10
      } else {
        doc.setFontSize(10)
        doc.setFont('helvetica', 'italic')
        doc.text('No campers assigned', 20, yPos)
        yPos += 10
      }
    }

    addFooter(doc, 1)

    const pdfBase64 = doc.output('datauristring')
    const filename = `group-roster-${camp.name.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pdf`

    return {
      data: {
        pdfBase64,
        filename,
        generatedAt: new Date().toISOString(),
      },
      error: null,
    }
  } catch (error) {
    console.error('[Reports] Failed to generate group report PDF:', error)
    return { data: null, error: error as Error }
  }
}

/**
 * List generated reports for a tenant
 */
export async function listReports(params: {
  tenantId: string
  type?: ReportType
  limit?: number
}): Promise<{
  data: {
    reports: {
      id: string
      type: string
      resourceId: string
      filename: string
      url: string | null
      status: string
      createdAt: string
    }[]
  } | null
  error: Error | null
}> {
  try {
    const { tenantId, type, limit = 50 } = params

    // Map our ReportType to Prisma's PdfReportType
    const typeMap: Record<ReportType, string> = {
      SESSION: 'session_report',
      DAY: 'camp_day_report',
      CURRICULUM: 'curriculum_export',
      GROUP: 'roster_export',
    }

    const reports = await prisma.pdfReport.findMany({
      where: {
        tenantId,
        ...(type ? { type: typeMap[type] as 'session_report' | 'camp_day_report' | 'curriculum_export' | 'roster_export' | 'financial_summary' } : {}),
      },
      orderBy: { createdAt: 'desc' },
      take: limit,
    })

    return {
      data: {
        reports: reports.map((r) => ({
          id: r.id,
          type: r.type,
          resourceId: r.resourceId,
          filename: r.fileName || 'report.pdf',
          url: r.url,
          status: r.status,
          createdAt: r.createdAt.toISOString(),
        })),
      },
      error: null,
    }
  } catch (error) {
    console.error('[Reports] Failed to list reports:', error)
    return { data: null, error: error as Error }
  }
}
